export type AuthErrorCode =
  | "AUTH_INVALID_CREDENTIALS"
  | "AUTH_USER_LOCKED"
  | "AUTH_USER_DISABLED"
  | "AUTH_TOKEN_INVALID"
  | "AUTH_TOKEN_EXPIRED"
  | "AUTH_TOKEN_STALE"
  | "AUTH_FORBIDDEN"
  | "AUTH_CONFIG_ERROR"
  | "AUTH_INTERNAL_ERROR";
